Fix/pagination
hackoregon/openelections pull request #787
Opened 2019-09-09 21:40 UTC by billoosijok

* Adds pagination to contributions table

2019-09-09 21:47 UTC, andrewbiang888 requested changes
Clean up a few things then looks good to me!

2019-09-09 21:47 UTC, andrewbiang888 commented on app/src/Pages/Portal/Contributions/ContributionsTable/TablePagination.js
> +  return (
Delete this if it's not being used

2019-09-09 21:47 UTC, andrewbiang888 commented on app/src/Pages/Portal/Contributions/index.js
> +    console.log(data);
```suggestion
   
```

2019-09-09 21:47 UTC, andrewbiang888 commented on app/src/components/Forms/FilterContributions/FilterContributions.js
> +  // orderBy: {
delete this too if it's not being used

2019-09-09 21:49 UTC, billoosijok commented on app/src/Pages/Portal/Contributions/ContributionsTable/TablePagination.js
> +  return (
Will do

2019-09-10 00:06 UTC, andrewbiang888 approved these changes
Nice job

2019-09-10 00:19 UTC, kdv24 commented
Nice work! It looks great.

Looks like there may still be a bit of an issue on pagination though; if I set it to 100 or 150, it shows a screwy `101-70 of 70`
<img width="732" alt="Screen Shot 2019-09-09 at 5 10 34 PM" src="https://user-images.githubusercontent.com/6107653/64574824-df975b80-d325-11e9-8615-958de4c3e1c7.png">

2019-09-10 03:13 UTC, merged